### ISSUE TITLE
stake snx

### ISSUE THREAD

**Issue by hadifalahi4142** [Synthetixio/SIPs#1472]
i stake 53 snx one year in synthetix but now is 0

0xC5250939aB0E1aAF6680D54A2b2154e59a43871e

**Comment by kaleb-keny** [comment]
Lol @hadifalahi4142 this is not the way to reach synthetix, go to discord. You got liquidated https://optimistic.etherscan.io/tx/0x16fa35b968725979d2d3874e067d42b7a243576f145a3892aa62025e2508f7fd
