### ISSUE TITLE
Unfork from ethereum/EIPs

### ISSUE THREAD

**Issue by MicahZoltu** [Synthetixio/SIPs#417]
About once a week, someone accidentally submits a PR against ethereum/EIPs, likely because GitHub does that by default.  This leads to a bit of noise in the EIPs repository and probably is frustrating for users that do it on accident.  It would be nice if this repository were detached so that the default behavior was as desired, which is that PRs are against this repository and not ethereum/EIPs.

This Stack Exchange comment suggests that you can get the GitHub virtual assistant bot to do it for you, assuming you are the repository owner: https://stackoverflow.com/questions/29326767/unfork-a-github-fork-without-deleting/41486339#comment116493608_29326840

**Comment by justinjmoses** [comment]
Apologies @MicahZoltu. Submitted - hopefully it won't take too long.

**Comment by justinjmoses** [comment]
this is done 🙏🏼
