### ISSUE TITLE
SNX Uniswap Pool Staking Incentives 

### ISSUE THREAD

**Issue by kicul88** [Synthetixio/SIPs#74]
**Simple Summary**
This SIP proposes to introduce SNX Uniswap pool staking incentives in order to improve SNX liquidity. Inspired by previous, highly successful incentive initiative, the aim of this initiative is to create deeper SNX/ETH Uniswap pool by diverting a portion of SNX inflation to SNX liquidity providers. This will bring less slippage for larger trades and potentially much higher volume. More importantly, this incentive will decentralize SNX liquidity, meaning liquidity will be supplied by broader range of uncorrelated parties, based all over the world. This will make SNX liquidity fundamentally more robust, less likely to vanish in a crisis and more indicative of a healthy market.

**Abstract**
This SIP formalises at the protocol level to divert a portion of SNX inflation into a pool to incentivise liquidity providers of the SNX/ETH pair in Uniswap.

**Motivation**
Inflationary monetary policy, introduced in March 2018, was designed with the aim to create a strong incentive for SNX holders to stake their tokens by minting synths. For providing debt liquidity, SNX holders are rewarded with additional SNX on top of exchange fee rewards. This has led to enormous participation, currently ~ 81% of SNX tokens are staked. At the same time, it largely reduced available supply from where SNX liquidity could be provided. Not only that, but because of high SNX staking rewards (currently around 1 SNX per 100 SNX staked, per week) market making became largely unattractive. With current SNX trade volume on Uniswap, fee of 0.3% per trade can't compete with 1% per week that holders get by staking SNX. That's why incentivizing SNX liquidity providers is necessary.

Now, let's analyze how large should weekly incentive be in order to create 1,000,000 SNX + 6,400 ETH deep pool. We can arrive at this number by calculating weekly SNX rewards from alternative use of those funds (minting SNX reward + sETH LP reward). 

weekly minting reward is (90% of inflation) ~ 1 SNX per 100 SNX staked
weekly sETH LP incentive is (5% of inflation) 72,000 SNX
SNX price is 0.0064 ETH
sETH pool is ~90,000 ETH deep (44,700 ETH + 45,500 sETH)

Minting reward (locked for 12 months) ~ 1,000,000 SNX / 100 = 10,000 SNX
sETH LP reward (unlocked) ~  6400/(6400+90000) * 72000 SNX = 4780 SNX
**Total  ~ 15,000 SNX or ~1.1% of weekly inflation**
 
*Because of decaying inflation, allocating fixed % of inflationary supply to SNX LPs will make sure that proportion between incentive initiatives stays constant.

**Specification**
See https://sips.synthetix.io/sips/sip-31
 
 
**Rationale**
By implementing SNX Uniswap staking incentives we can largely improve SNX liquidity, both quantitatively (deeper pool and increased volume) and qualitatively (decentralized, more robust and healthier liquidity). 
Test Cases
 
**Implementation**

**Comment by 1053r** [comment]
SNX uniswap pool incentives should be locked for a year similar to how SNX inflationary rewards.
