### ISSUE TITLE
SNX Auction Trial

### ISSUE THREAD

**Issue by kaiynne** [Synthetixio/SIPs#76]
As per recent discord discussions the current arb pool is less efficient than it could be and has poor incentive alignment. An alternative mechanism I proposed was to hold a weekly SNX auction where SNX escrowed for 12 months is sold at a discount in a dutch auction. The proceeds of this auction will be used to buy sETH from the Uniswap sETH pool putting upward pressure on the peg. In order to determine whether this mechanism is viable I am proposing to run a trial at Thursday 23:00 UTC time (10am AEST on Friday).

1. 100k SNX will be auctioned 
2. The trial will run for 2.5h
3. The SNX price in ETH will be fixed at the opening of the auction
4. The initial discount will be 2%
5. Every 30 mins the discount will increase by 2%
6. The maximum discount will be 10%
7. All orders will be filled at the highest discount rate

To illustrate, if a bid for 80k SNX is placed at 2% and then 0 bids at 4% and 6% but then a bid for 20k SNX is placed at an 8% discount all SNX will be sold at the 8% discount. If there is an excess of demand at a specific discount level the initial bids at earlier levels will all be filled and then the final discount level will be distributed pro rata.

This manual trial will require a level of trust as discounts will be calculated manually and SNX will be distributed at the close of the auction, but the ETH must be sent during the auction to confirm and lock in a bid. If the trial is successful a contract will be written to automate this process later. To provide an additional level of assurance a gnosis multisig will be used as the address to receive the proceeds with a trusted community member acting as a second signer.

**Comment by degenspartan** [comment]
Clarifications:

This Thursday, 16th Jan? If so, I think it would be a bit rushed. For auctions to succeed, we need a healthy number of informed participants, but most importantly, they must also have liquidity on them to take part in the auction.

How will the auction be run? A view-only channel in the discord, where the auctioneer is the only speaker? Auctioneer announces rules, instructions, start, steps and final closing? Discount cut-off is roughly by timing, followed by the auctioneer having the final say and announcing the cut-off block to qualify for each discount tier? Will there be an live channel, counting the bids and cumulative volume as they flow in? Should the final eligible discount tier be distributed pro-rata, or first come first serve? Or is it pro-rata to avoid gas wars? Are we going to do 100k in the first auction? How about a lower amount?

By the way, I like this idea a lot!

**Comment by dliuproduction** [comment]
I believe it is Thursdays every week.
