### ISSUE TITLE
Synth exchange pausing for spot market closures

### ISSUE THREAD

**Issue by garthtravers** [Synthetixio/SIPs#79]
From the [announcement](https://blog.synthetix.io/chainlink-decentralizes-first-wave-of-synthetix-price-feeds/) of transitioning to Chainlink oracles for FX currencies: 
> Given FX markets close over the weekend, and there is currently no mechanism to pause trading, there is a small chance of a positive black swan event if a fiat currency is expected to experience major price appreciation over a weekend. The Synthetix team is aware of this possibility, and is investigating solutions.

FX currencies typically don't move much over a weekend, but it is possible, and it's likely to become more of an issue when synthetic stocks are launched in the future. For this reason, it's important to start a conversation about what mechanism/s can be built into the Synths to combat this.

**Comment by justinjmoses** [comment]
Bundled into PR #95
