### ISSUE TITLE
eSNX an ERC-20 token redeemable for escrowed SNX

### ISSUE THREAD

**Issue by kaiynne** [Synthetixio/SIPs#90]
As part of our ongoing trial of the SNX auction mechanism we need a way to automatically distribute escrowed SNX. This has previously been either manually administered or implemented at the protocol level, eg. SNX staking rewards. However, this creates a lack of flexibility in how escrowed SNX is distributed. This issue proposes a contract that enable three functions:

1. minting eSNX (private function) -  as part of the Synthetix Inflationary supply the RewardsDistribution contract will be configured to send an amount of SNX to this eSNX Contract and then call RewardsDistributionRecipient.notifyRewardAmount(amount) so eSNX can mint eSNX the equal amount of eSNX for SNX then send the SNX to the RewardsEscrow contract and send the eSNX minted to the configurable(ownerOnly) auction contract address.  

2. minting eSNX (public function) - after calling SNX.approve(amount, eSNXAddress) anyone can call this function with an amount of SNX to transfer it to the escrow contract and mint eSNX and send back to the caller so they can sell escrowed SNX. 

3. eSNX redemption (public function)- sending eSNX to the contract will burn eSNX and create a vesting entry in the escrow contract. 
Note: this is not currently possible other than some access given via the FeePool

This will allow for a transferable version of escrowed SNX that can be used to incentivise beneficial actions for the protocol.  This eSNX will not function as collateral and can only be converted to SNX once and will then be locked to the account it is assigned to.

**Comment by CryptoToit** [comment]
Very cool idea. 

Can this not also be used in the future "Liquidation" mechanism we have been talking about a lot in the past? If an account get partially or completely liquidated there has to be a way to get access to the Escrowed SNX. This could work perfectly.
